Repository pulumi/actions, pull requests merged in 2022-11, with the labels that each got.

#755 feat: Add optional project_name to action
  CHANGELOG.md
  src/libs/__tests__/pr.test.ts
  src/libs/pr.ts
  src/main.ts
Labels: kind/bug, impact/reliability, area/cicd

#756 clarify stack name
  README.md
Labels: impact/no-changelog-required

#775 Update changelog for 3.20.0
  CHANGELOG.md
Labels: kind/engineering, impact/no-changelog-required, area/docs

#747 docs: Add example for Google Workflow Identity Federation
  examples/nodejs-google-workload-identity-federation.yaml
Labels: impact/no-changelog-required
