Repository pulumi/actions, pull requests merged in 2022-07, with the labels that each got.

#662 feat: Support colorized output
  CHANGELOG.md
  README.md
  action.yml
  src/__tests__/config.test.ts
  src/config.ts
Labels: kind/enhancement, impact/usability, area/cicd

#675 Add release schedule and description of cadence.
  README.md
Labels: impact/no-changelog-required, area/docs

#676 Update README with release process.
  CONTRIBUTING.md
  README.md
Labels: kind/enhancement, impact/no-changelog-required, area/docs

#679 Only "Comment-On-PRs" when running in a PR context
  CHANGELOG.md
  src/__tests__/config.test.ts
  src/config.ts
  src/main.ts
Labels: p1, kind/bug, impact/regression, impact/panic, area/cicd

#680 Update CHANGELOG with release notes.
  CHANGELOG.md
Labels: kind/enhancement, impact/changelog, area/docs

#685 Prevent Command Substitution in bash step
  .github/workflows/test.yml
Labels: kind/bug, impact/no-changelog-required, impact/flaky-test, area/cicd

#661 Add `pulumi-version` option
  .gitignore
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  action.yml
  package.json
  src/__tests__/config.test.ts
  src/config.ts
  src/libs/pulumi-cli.ts
  src/main.ts
Labels: kind/enhancement, impact/usability, area/cicd

#693 Clarify one-feature-per-pr in CONTRIBUTING.md
  CONTRIBUTING.md
Labels: impact/no-changelog-required, area/docs
