Repository pulumi/actions, pull requests merged in 2023-01, with the labels that each got.

#843 Correct typo in action name.
  examples/nodejs-aws.yaml
Labels: impact/no-changelog-required

#842 README: Alphabetize extra options, add policy pack descriptions
  README.md
Labels: impact/no-changelog-required

#846 Cut release of v3.21.0
  CHANGELOG.md
Labels: impact/no-changelog-required, area/docs

#753 feat: update action runtime to NodeJS 16
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  action.yml
  examples/dotnet-pulumi.yaml
  examples/go-pulumi.yaml
  examples/nodejs-aws.yaml
  examples/nodejs-azure.yaml
  examples/nodejs-google.yaml
  examples/nodejs-local.yaml
  examples/nodejs-pulumi.yaml
  examples/python-pulumi.yaml
  src/__tests__/config.test.ts
  src/config.ts
Labels: impact/breaking, blocked, awaiting-upstream, kind/bug, dependencies

#803 allow PR comment from non-PR events using `comment-on-pr-number`
  CHANGELOG.md
  README.md
  src/libs/__tests__/pr.test.ts
  src/main.ts
Labels: area/cicd
